#
#	Copyright (c) 2013	Montage Inc.	All rights reserved. 
#
obj-$(CONFIG_CHEETAH) += generic/

# Ethernet
obj-$(CONFIG_CHEETAH_ETH) += eth/

#WiFi
#obj-$(CONFIG_CHEETAH_WLA) += wla/

#Bridge
obj-$(CONFIG_CHEETAH_BRG) += bridge/

#SDHCI
obj-$(CONFIG_CHEETAH_SDHCI) += mmc/

#Sound
obj-$(CONFIG_CHEETAH_SND) += sound/

#obj-$(CONFIG_EARLY_PRINTK)	+=

#EXTRA_CFLAGS += -Werror
#
# 	Uncomment to use Switch Port0 as WAN port
#
#EXTRA_CFLAGS += -DCML_WAN_P0
